//
// Input file for "my2c.ex"

// Automatically Generated by "my2c.ex"


// Code begins:

#include "test.jjc.hpp"


int main(int argc, char* argv[]) // or char** argv
{
int a;

	std::cout << "hi world " <<
		  (4*(2)) << std::endl;
	puts( "ok" );
	puts( "good" );
	// Default return (0)
	return 0;
}

// End of file.
